/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

  module.exports = {
    resources: [
      {
        type: 'category',
        label: 'Resources',
        link: {
          type: 'generated-index',
          title: 'Resources',
          //description: 'Learn about the most important Docusaurus concepts!',
          slug: '/category/Resources',
          keywords: ['resources']
         // image: '/img/docusaurus.png',
        },
        items: ['intro','links','license'],
      },
    ], 
    methods: [

      {
        type: 'category',
        label: 'Methodology',
        link: {
          type: 'generated-index',
          title: 'Methodology',
          //description: 'Learn about the most important Docusaurus concepts!',
          slug: '/category/methods',
          keywords: ['methods']
         // image: '/img/docusaurus.png',
        },
        items: ['Technical Reference/overview', 
        //"Technical Reference/Components/Additional Information/A_Appendix A - Regional HSPF Calibration Factors",
        "Technical Reference/Components/High-resolution Land Cover",
        "Technical Reference/Components/Hydrology",
        "Technical Reference/Components/Water Quality Statistics",
        "Technical Reference/Components/Additional Information/References",
      
      ],

      },


    ], 
    layers: [
      {
      type: 'category',
      label: 'Data Layers',
      link: {
        type: 'generated-index',
        title: 'Data Layers',
        description: 'Documentation of layer sources and information.',
        slug: '/category/DataLayers',
        keywords: ['guides']
       // image: '/img/docusaurus.png',
      },
      items: [
        "Data Layers/age_of_imperviousness",
        "Data Layers/flow_duration_index",
        "Data Layers/hspf_land_cover_type",
        "Data Layers/hydrologic_response_units",
        "Data Layers/imperviousness",
        "Data Layers/land_cover",
        "Data Layers/land_use",
        "Data Layers/pollutant_concentration",
        "Data Layers/pollutant_load",
        "Data Layers/population_density",
        "Data Layers/precipitation",
        "Data Layers/runoff",
        "Data Layers/slope",
        "Data Layers/slope_categories",
        "Data Layers/soils",
        "Data Layers/traffic",

      ],
    }
    ]
  

  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
//   "Reference": {'Overview': ['Technical Reference/overview'], 
// }, 
// "layerSidebar": ['Data Layers/land_cover']

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
